linters:
  disable-all: true
  enable:
    - bodyclose
#    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
#    - goimports
#    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

    - asciicheck
#    - gochecknoglobals
    - gocognit
#    - godot
    - godox
    - goerr113
    - nestif
    - prealloc
    - testpackage
    - wsl

run:
  skip-dirs:
    - ./internal/repo/models