services:
  app:
    env_file:
      - app/.env
    build:
      context: ../
      dockerfile: deploy/app/Dockerfile
    volumes:
      - ../:/app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    volumes:
      - ../.data:/var/lib/postgresql/data